# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
creator: Lv Honghao
title: Honghao Lv
subtitle: Honghao's personal blog
welcome_message: <a href="/assets/documents/HonghaoLyu_CV.pdf" target="_blank">Download my CV</a>
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 Some sharing and posts of my daily and research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
chinese_button:
    title: 中文
    description: My Chinese Main Page

english_button:
    title: English
    description: My English Main Page

# Social
social:
    # weibo: 2606809017
    github: HonghaoLYU
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: lvhonghao@zju.edu.cn
    # bilibili: 38758994
    weixin: vfDi7-TYXTorn6lHvJ6fGw
    researchgate: Honghao_Lv2
    googlescholar: 4DrzwMcAAAAJ&hl=en